version: '3'

services:
  php-fpm:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    working_dir: /var/www/app/public
    volumes:
      - ../src:/var/www/app

  nginx:
    image: 'nginx'
    depends_on:
      - php-fpm
    build:
      context: ./nginx
      dockerfile: Dockerfile
    working_dir: /var/www/app/public
    volumes:
      - ../src:/var/www/app
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "8080:8080"
      - "4433:4433"